product.property=Product Profile Dev

##########################################
#  PARAMETROS DE CONFIGURACION
##########################################
app.testProp=Property of test Update 1

##########################################
#  CONFIGURACION MONGODB
##########################################
spring.data.mongodb.uri=mongodb://localhost:27017/productdb